---

- name: Remove vscode settings direcotry
  ansible.builtin.file:
    path: "{{ vscode_user_settings_path }}"
    state: "absent"

- name: Remove unused dependencies
  become: true
  ansible.builtin.package:
    autoremove: true

...
