---

- name: Install debian specific package_facts dependency
  become: true
  when: ansible_distribution == "Debian"
  ansible.builtin.package:
    name: python-apt-common
    state: present

- name: Gather package facts
  ansible.builtin.package_facts:

- name: Check if VSCode is present and accessible
  become: true
  become_user: "{{ user }}"
  ansible.builtin.command:
    cmd: code --version
  changed_when: false

- name: Prepare settings
  when: vscode_extensions
  ansible.builtin.include_tasks:
    file: settings.yml

- name: Set up extensions
  when: vscode_extensions
  ansible.builtin.include_tasks:
    file: extensions.yml

- name: Add vscode to gnome favorites
  when: "'gnome-shell' in ansible_facts.packages and vscode_gnome_favorite"
  ansible.builtin.include_tasks:
    file: favorite.yml

...
